.TH "CCEXT\-CLI" "1" "August 2021" "2.1.1" "ClipCC Extension CLI Manual"
.SH "NAME"
\fBccext-cli\fR
.QP
.P
The interactive command line utility for creating ClipCC extensions

.
.P
A detailed guide on the making of a ClipCC extension is available at \fIhttps://github\.com/Clipteam/clipcc\-extension/blob/master/README\.md\fR
.SH SYNOPSIS
.P
\fBccext\-cli [\-\-help] [\-v]\fP
.SH DESCRIPTION
.P
ccext\-cli is the interactive command line utility for creating ClipCC extensions\.
.P
Run ccext\-cli in a directory to set it up for ClipCC extension development\.
.SH OPTIONS
.P
\fB\-\-help\fP
    Display help information
.P
\fB\-v\fP, \fB\-\-version\fP
    Show version number
.SH LICENSE
.P
Copyright (c) 2021, The ClipCC contributors (MIT License)\.
.SH SEE ALSO
.P
npm(1)

